"""Updated MedicalRecord

Revision ID: 09bd8901c695
Revises: a8aabfba3df3
Create Date: 2026-05-26 17:52:24.361994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09bd8901c695'
down_revision: Union[str, Sequence[str], None] = 'a8aabfba3df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('created_by_id', sa.UUID(), nullable=True))
    op.add_column('medical_records', sa.Column('updated_by_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'medical_records', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'medical_records', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint('uq_patient_family_link', 'patient_family_links', ['primary_patient_id', 'family_member_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_patient_family_link', 'patient_family_links', type_='unique')
    op.drop_constraint(None, 'medical_records', type_='foreignkey')
    op.drop_constraint(None, 'medical_records', type_='foreignkey')
    op.drop_column('medical_records', 'updated_by_id')
    op.drop_column('medical_records', 'created_by_id')
    # ### end Alembic commands ###
