"""added updated_by in clinicalencounter

Revision ID: 2fe9de521ca4
Revises: 347c057856ee
Create Date: 2026-06-08 18:30:47.931636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fe9de521ca4'
down_revision: Union[str, Sequence[str], None] = '347c057856ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_encounters', sa.Column('updated_by_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'clinical_encounters', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clinical_encounters', type_='foreignkey')
    op.drop_column('clinical_encounters', 'updated_by_id')
    # ### end Alembic commands ###
