"""added ClinicalEncounter models

Revision ID: 347c057856ee
Revises: 9cda94581a1c
Create Date: 2026-06-03 17:24:52.913261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '347c057856ee'
down_revision: Union[str, Sequence[str], None] = '9cda94581a1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_encounters',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'CLOSED', 'VOID', name='encounter_status_enum'), nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('bp_systolic', sa.Integer(), nullable=True),
    sa.Column('bp_diastolic', sa.Integer(), nullable=True),
    sa.Column('pulse_rate', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('spo2', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id')
    )
    op.create_index(op.f('ix_clinical_encounters_patient_id'), 'clinical_encounters', ['patient_id'], unique=False)
    op.create_index(op.f('ix_clinical_encounters_tenant_id'), 'clinical_encounters', ['tenant_id'], unique=False)
    op.create_index('ix_encounters_tenant_patient', 'clinical_encounters', ['tenant_id', 'patient_id'], unique=False)
    op.create_table('clinical_examination_entries',
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('field_id', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['clinical_encounters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('encounter_id', 'field_id', name='uq_exam_field_per_encounter')
    )
    op.create_index(op.f('ix_clinical_examination_entries_encounter_id'), 'clinical_examination_entries', ['encounter_id'], unique=False)
    op.create_index('ix_exam_encounter', 'clinical_examination_entries', ['encounter_id'], unique=False)
    op.create_table('clinical_findings',
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('finding_code', sa.String(length=200), nullable=False),
    sa.Column('finding_name', sa.String(length=200), nullable=False),
    sa.Column('tooth_numbers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['clinical_encounters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_findings_encounter_id'), 'clinical_findings', ['encounter_id'], unique=False)
    op.create_table('encounter_diagnoses',
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_code', sa.String(length=200), nullable=False),
    sa.Column('diagnosis_name', sa.String(length=200), nullable=False),
    sa.Column('icd10_code', sa.String(length=20), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('tooth_numbers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['clinical_encounters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_diagnosis_encounter', 'encounter_diagnoses', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_encounter_diagnoses_encounter_id'), 'encounter_diagnoses', ['encounter_id'], unique=False)
    op.create_table('encounter_medical_histories',
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_diabetic', sa.Boolean(), nullable=True),
    sa.Column('has_hypertension', sa.Boolean(), nullable=True),
    sa.Column('has_heart_condition', sa.Boolean(), nullable=True),
    sa.Column('has_medication_allergy', sa.Boolean(), nullable=True),
    sa.Column('is_on_blood_thinners', sa.Boolean(), nullable=True),
    sa.Column('has_hepatitis_tb', sa.Boolean(), nullable=True),
    sa.Column('is_pregnant', sa.Boolean(), nullable=True),
    sa.Column('smokes_or_drinks', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['clinical_encounters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('encounter_id')
    )
    op.create_table('investigations',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('investigation_code', sa.String(length=200), nullable=False),
    sa.Column('investigation_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='investigation_status_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('result_file_url', sa.String(length=500), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['clinical_encounters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigations_encounter_id'), 'investigations', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_investigations_tenant_id'), 'investigations', ['tenant_id'], unique=False)
    op.create_table('treatment_plans',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'PARTIALLY_COMPLETED', 'CANCELLED', name='treatment_plan_status_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('estimated_total_cost', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['clinical_encounters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('encounter_id')
    )
    op.create_index(op.f('ix_treatment_plans_patient_id'), 'treatment_plans', ['patient_id'], unique=False)
    op.create_index(op.f('ix_treatment_plans_tenant_id'), 'treatment_plans', ['tenant_id'], unique=False)
    op.create_table('treatment_plan_items',
    sa.Column('treatment_plan_id', sa.UUID(), nullable=False),
    sa.Column('procedure_catalog_id', sa.UUID(), nullable=False),
    sa.Column('tooth_numbers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('visit_number', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'DONE', 'DEFERRED', 'CANCELLED', 'CHANGED', name='treatment_plan_item_status_enum'), nullable=False),
    sa.Column('performed_procedure_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['performed_procedure_id'], ['procedures.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['procedure_catalog_id'], ['procedure_catalogs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['treatment_plan_id'], ['treatment_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_plan_items_treatment_plan_id'), 'treatment_plan_items', ['treatment_plan_id'], unique=False)
    op.add_column('procedures', sa.Column('encounter_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'procedures', 'clinical_encounters', ['encounter_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'procedures', type_='foreignkey')
    op.drop_column('procedures', 'encounter_id')
    op.drop_index(op.f('ix_treatment_plan_items_treatment_plan_id'), table_name='treatment_plan_items')
    op.drop_table('treatment_plan_items')
    op.drop_index(op.f('ix_treatment_plans_tenant_id'), table_name='treatment_plans')
    op.drop_index(op.f('ix_treatment_plans_patient_id'), table_name='treatment_plans')
    op.drop_table('treatment_plans')
    op.drop_index(op.f('ix_investigations_tenant_id'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_encounter_id'), table_name='investigations')
    op.drop_table('investigations')
    op.drop_table('encounter_medical_histories')
    op.drop_index(op.f('ix_encounter_diagnoses_encounter_id'), table_name='encounter_diagnoses')
    op.drop_index('ix_diagnosis_encounter', table_name='encounter_diagnoses')
    op.drop_table('encounter_diagnoses')
    op.drop_index(op.f('ix_clinical_findings_encounter_id'), table_name='clinical_findings')
    op.drop_table('clinical_findings')
    op.drop_index('ix_exam_encounter', table_name='clinical_examination_entries')
    op.drop_index(op.f('ix_clinical_examination_entries_encounter_id'), table_name='clinical_examination_entries')
    op.drop_table('clinical_examination_entries')
    op.drop_index('ix_encounters_tenant_patient', table_name='clinical_encounters')
    op.drop_index(op.f('ix_clinical_encounters_tenant_id'), table_name='clinical_encounters')
    op.drop_index(op.f('ix_clinical_encounters_patient_id'), table_name='clinical_encounters')
    op.drop_table('clinical_encounters')
    # ### end Alembic commands ###
