
"""Added Patient and Medical Record Model

Revision ID: 399ff69580fd
Revises: fd8fc40cf5f0
Create Date: 2026-05-25 19:52:41.967400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '399ff69580fd'
down_revision: Union[str, Sequence[str], None] = 'fd8fc40cf5f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('patient_code', sa.String(length=30), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender_enum'), nullable=False),
    sa.Column('blood_group', sa.Enum('A_POSITIVE', 'A_NEGATIVE', 'B_POSITIVE', 'B_NEGATIVE', 'AB_POSITIVE', 'AB_NEGATIVE', 'O_POSITIVE', 'O_NEGATIVE', name='blood_group_enum'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('allergies', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'BLACKLISTED', name='patient_status_enum'), nullable=False),
    sa.Column('category', sa.Enum('REGULAR', 'VIP', 'INSURANCE', 'NEW', 'CHILD', 'SENIOR', name='patient_category_enum'), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('last_visit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('primary_account_id', sa.UUID(), nullable=True),
    sa.Column('family_relation', sa.Enum('SELF', 'SPOUSE', 'CHILD', 'PARENT', 'OTHER', name='family_relation_enum'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['primary_account_id'], ['patients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'patient_code', name='uq_patient_code_per_tenant'),
    sa.UniqueConstraint('tenant_id', 'phone', name='uq_patient_phone_per_tenant')
    )
    op.create_index('idx_patient_search', 'patients', ['first_name', 'last_name', 'phone', 'email'], unique=True)
    op.create_index(op.f('ix_patients_tenant_id'), 'patients', ['tenant_id'], unique=False)
    op.create_table('medical_records',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('primary_doctor_id', sa.UUID(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('insurance_provider', sa.String(length=255), nullable=True),
    sa.Column('insurance_number', sa.String(length=100), nullable=True),
    sa.Column('systemic_conditions', sa.String(length=500), nullable=True),
    sa.Column('current_medications', sa.String(length=500), nullable=True),
    sa.Column('prior_surgeries', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['primary_doctor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medical_records')
    op.drop_index(op.f('ix_patients_tenant_id'), table_name='patients')
    op.drop_index('idx_patient_search', table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
