"""removed finding_name and diagnosis_name

Revision ID: 4c9d4bdddd34
Revises: 2fe9de521ca4
Create Date: 2026-06-09 15:51:52.682734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c9d4bdddd34'
down_revision: Union[str, Sequence[str], None] = '2fe9de521ca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinical_findings', 'finding_name')
    op.drop_column('encounter_diagnoses', 'diagnosis_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('encounter_diagnoses', sa.Column('diagnosis_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('clinical_findings', sa.Column('finding_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
