"""added closed_by_id for encounter

Revision ID: 57d5f0b4070a
Revises: c4a2031aaba8
Create Date: 2026-06-10 18:23:01.731780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57d5f0b4070a'
down_revision: Union[str, Sequence[str], None] = 'c4a2031aaba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TYPE treatment_plan_item_status_enum
        ADD VALUE IF NOT EXISTS 'DEFERRED';
        """
    )
    op.add_column('clinical_encounters', sa.Column('closed_by_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'clinical_encounters', 'users', ['closed_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clinical_encounters', type_='foreignkey')
    op.drop_column('clinical_encounters', 'closed_by_id')
    # ### end Alembic commands ###
