"""Added created_by and updated_by in Patient Model for auditing

Revision ID: 5dc8ff00f7b9
Revises: 399ff69580fd
Create Date: 2026-05-25 20:34:11.022691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dc8ff00f7b9'
down_revision: Union[str, Sequence[str], None] = '399ff69580fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('allergies', sa.String(length=500), nullable=True))
    op.add_column('patients', sa.Column('created_by_id', sa.UUID(), nullable=True))
    op.add_column('patients', sa.Column('updated_by_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'patients', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'patients', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_column('patients', 'updated_by_id')
    op.drop_column('patients', 'created_by_id')
    op.drop_column('medical_records', 'allergies')
    # ### end Alembic commands ###
