"""Added relationship between ProcedureCatalog and AppointmentProcedure

Revision ID: 911000fbc360
Revises: d60a9e406161
Create Date: 2026-05-27 21:00:44.353169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '911000fbc360'
down_revision: Union[str, Sequence[str], None] = 'd60a9e406161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_appointment_planned_procedure'), 'appointment_procedures', type_='unique')
    op.create_unique_constraint('uq_appointment_planned_procedure', 'appointment_procedures', ['appointment_id', 'procedure_catalog_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_appointment_planned_procedure', 'appointment_procedures', type_='unique')
    op.create_unique_constraint(op.f('uq_appointment_planned_procedure'), 'appointment_procedures', ['appointment_id', 'procedure_catalog_id', 'tooth_numbers'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
