"""Removed allergies from Patient

Revision ID: 9cb9cce4ff5e
Revises: 5dc8ff00f7b9
Create Date: 2026-05-25 20:37:25.723405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cb9cce4ff5e'
down_revision: Union[str, Sequence[str], None] = '5dc8ff00f7b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'allergies')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('allergies', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
