"""Updated PatientFamilyLink model

Revision ID: a8aabfba3df3
Revises: be9ad00b817e
Create Date: 2026-05-26 16:57:53.589902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8aabfba3df3'
down_revision: Union[str, Sequence[str], None] = 'be9ad00b817e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_family_links', sa.Column('created_by_id', sa.UUID(), nullable=True))
    op.add_column('patient_family_links', sa.Column('updated_by_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'patient_family_links', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'patient_family_links', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patient_family_links', type_='foreignkey')
    op.drop_constraint(None, 'patient_family_links', type_='foreignkey')
    op.drop_column('patient_family_links', 'updated_by_id')
    op.drop_column('patient_family_links', 'created_by_id')
    # ### end Alembic commands ###
