"""Added PatientFamilyLink model for better linking of patient members

Revision ID: be9ad00b817e
Revises: 9cb9cce4ff5e
Create Date: 2026-05-26 16:47:26.864518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be9ad00b817e'
down_revision: Union[str, Sequence[str], None] = '9cb9cce4ff5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_family_links',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('primary_patient_id', sa.UUID(), nullable=False),
    sa.Column('family_member_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('SPOUSE', 'SON', 'DAUGHTER', 'FATHER', 'MOTHER', 'BROTHER', 'SISTER', 'OTHER', name='family_relationship_enum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['family_member_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['primary_patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_family_links_tenant_id'), 'patient_family_links', ['tenant_id'], unique=False)
    op.drop_index(op.f('idx_patient_search'), table_name='patients')
    op.create_index('idx_patient_search', 'patients', ['first_name', 'last_name', 'phone', 'email'], unique=False)
    op.drop_constraint(op.f('patients_primary_account_id_fkey'), 'patients', type_='foreignkey')
    op.drop_column('patients', 'family_relation')
    op.drop_column('patients', 'primary_account_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('primary_account_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('family_relation', postgresql.ENUM('SELF', 'SPOUSE', 'CHILD', 'PARENT', 'OTHER', name='family_relation_enum'), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('patients_primary_account_id_fkey'), 'patients', 'patients', ['primary_account_id'], ['id'], ondelete='SET NULL')
    op.drop_index('idx_patient_search', table_name='patients')
    op.create_index(op.f('idx_patient_search'), 'patients', ['first_name', 'last_name', 'phone', 'email'], unique=True)
    op.drop_index(op.f('ix_patient_family_links_tenant_id'), table_name='patient_family_links')
    op.drop_table('patient_family_links')
    # ### end Alembic commands ###
