"""removed investigation_name

Revision ID: c4a2031aaba8
Revises: 4c9d4bdddd34
Create Date: 2026-06-09 19:04:31.834556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4a2031aaba8'
down_revision: Union[str, Sequence[str], None] = '4c9d4bdddd34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investigations', 'investigation_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investigations', sa.Column('investigation_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
