"""Added relationship for appointment and patient

Revision ID: d60a9e406161
Revises: 6eed2fbb9c53
Create Date: 2026-05-27 16:56:39.890245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd60a9e406161'
down_revision: Union[str, Sequence[str], None] = '6eed2fbb9c53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('assigned_doctor_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.create_index(op.f('ix_appointments_assigned_doctor_id'), 'appointments', ['assigned_doctor_id'], unique=False)
    op.drop_constraint(op.f('appointments_doctor_id_fkey'), 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'users', ['assigned_doctor_id'], ['id'], ondelete='SET NULL')
    op.drop_column('appointments', 'doctor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('doctor_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key(op.f('appointments_doctor_id_fkey'), 'appointments', 'users', ['doctor_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_appointments_assigned_doctor_id'), table_name='appointments')
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.drop_column('appointments', 'assigned_doctor_id')
    # ### end Alembic commands ###
