"""Added revoked_at field in UserSession

Revision ID: d77ccdaa1d4c
Revises: cf1eb78f3985
Create Date: 2026-05-22 15:34:48.497609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd77ccdaa1d4c'
down_revision: Union[str, Sequence[str], None] = 'cf1eb78f3985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_sessions', 'revoked_at')
    # ### end Alembic commands ###
