from app.taxonomy.types import ExamField

ON_EXAMINATION_TAXONOMY: dict[str, list[ExamField]] = {
    "General Examination": [
        ExamField("gen_built",           "Built and nourishment",               "text"),
        ExamField("gen_height_weight",   "Height & Weight",                     "text"),
        ExamField("gen_gait",            "Gait and posture",                    "text"),
        ExamField("gen_vitals",          "Vital signs (BP, Pulse, Temp, Resp)", "text"),
        ExamField("gen_pallor",          "Pallor",                              "checkbox"),
        ExamField("gen_icterus",         "Icterus",                             "checkbox"),
        ExamField("gen_cyanosis",        "Cyanosis",                            "checkbox"),
        ExamField("gen_clubbing",        "Clubbing",                            "checkbox"),
        ExamField("gen_edema",           "Edema",                               "checkbox"),
        ExamField("gen_lymphadenopathy", "Lymphadenopathy",                     "checkbox"),
    ],
    "Extraoral Examination": [
        ExamField("ext_symmetry",      "Facial symmetry/asymmetry", "select", ("Symmetrical", "Asymmetrical")),
        ExamField("ext_profile",       "Profile",                   "select", ("Straight", "Convex", "Concave")),
        ExamField("ext_tmj",           "TMJ examination",           "text"),
        ExamField("ext_mouth_opening", "Mouth opening",             "text"),
        ExamField("ext_swelling",      "Facial swelling",           "checkbox"),
        ExamField("ext_tenderness",    "Tenderness",                "checkbox"),
        ExamField("ext_lymph_node",    "Lymph node examination",    "text"),
        ExamField("ext_lip_competence","Lip competence",            "select", ("Competent", "Incompetent")),
        ExamField("ext_scars",         "Skin lesions/scars",        "checkbox"),
        ExamField("ext_mandibular",    "Mandibular movements",      "text"),
    ],
    "Intraoral Soft Tissue Examination": [
        ExamField("int_hygiene",   "Oral hygiene status", "select", ("Good", "Fair", "Poor")),
        ExamField("int_gingival",  "Gingival condition",  "text"),
        ExamField("int_bleeding",  "Bleeding on probing", "checkbox"),
        ExamField("int_calculus",  "Calculus deposits",   "select", ("None", "Mild", "Moderate", "Severe")),
        ExamField("int_pockets",   "Periodontal pockets", "checkbox"),
        ExamField("int_mobility",  "Tooth mobility",      "checkbox"),
        ExamField("int_mucosal",   "Mucosal lesions",     "checkbox"),
        ExamField("int_tongue",    "Tongue examination",  "text"),
        ExamField("int_floor",     "Floor of mouth examination", "text"),
        ExamField("int_palate",    "Palate examination",  "text"),
        ExamField("int_vestibular","Vestibular depth",    "text"),
        ExamField("int_salivary",  "Salivary flow",       "select", ("Normal", "Dry mouth", "Hypersalivation")),
    ],
    "Hard Tissue Examination": [
        ExamField("hard_caries",        "Dental caries",         "checkbox"),
        ExamField("hard_restored",      "Restored teeth",        "checkbox"),
        ExamField("hard_missing",       "Missing teeth",         "checkbox"),
        ExamField("hard_fractured",     "Fractured teeth",       "checkbox"),
        ExamField("hard_attrition",     "Attrition",             "checkbox"),
        ExamField("hard_abrasion",      "Abrasion",              "checkbox"),
        ExamField("hard_erosion",       "Erosion",               "checkbox"),
        ExamField("hard_malocclusion",  "Malocclusion",          "checkbox"),
        ExamField("hard_crowding",      "Crowding",              "checkbox"),
        ExamField("hard_spacing",       "Spacing",               "checkbox"),
        ExamField("hard_impacted",      "Impacted teeth",        "checkbox"),
        ExamField("hard_discoloration", "Tooth discoloration",   "checkbox"),
        ExamField("hard_sensitivity",   "Sensitivity",           "checkbox"),
        ExamField("hard_percussion",    "Percussion tenderness", "checkbox"),
    ],
    "Periodontal Examination": [
        ExamField("perio_enlargement",    "Gingival enlargement", "checkbox"),
        ExamField("perio_recession",      "Gingival recession",   "text"),
        ExamField("perio_pocket_depth",   "Pocket depth",         "text"),
        ExamField("perio_furcation",      "Furcation involvement","select", ("None", "Grade I", "Grade II", "Grade III")),
        ExamField("perio_plaque_index",   "Plaque index",         "text"),
        ExamField("perio_calculus_index", "Calculus index",       "text"),
    ],
    "Orthodontic Examination": [
        ExamField("ortho_molar",    "Molar relation",      "select", ("Class I", "Class II Div 1", "Class II Div 2", "Class III")),
        ExamField("ortho_canine",   "Canine relation",     "select", ("Class I", "Class II", "Class III")),
        ExamField("ortho_overjet",  "Overjet",             "text"),
        ExamField("ortho_overbite", "Overbite",            "text"),
        ExamField("ortho_midline",  "Midline discrepancy", "text"),
        ExamField("ortho_crossbite","Crossbite",           "checkbox"),
        ExamField("ortho_openbite", "Open bite",           "checkbox"),
        ExamField("ortho_deepbite", "Deep bite",           "checkbox"),
    ],
    "Prosthodontic Examination": [
        ExamField("prostho_spaces",    "Edentulous spaces",      "text"),
        ExamField("prostho_ridge",     "Ridge form",             "select", ("High well-rounded", "Flat", "Knife-edge", "Resorbed")),
        ExamField("prostho_stability", "Denture stability",      "select", ("Good", "Fair", "Poor")),
        ExamField("prostho_retention", "Retention of prosthesis","select", ("Good", "Fair", "Poor")),
        ExamField("prostho_occlusion", "Occlusion examination",  "text"),
    ],
    "Endodontic Examination": [
        ExamField("endo_vitality",  "Pulp vitality test",       "text"),
        ExamField("endo_thermal",   "Thermal test",             "text"),
        ExamField("endo_electric",  "Electric pulp test",       "text"),
        ExamField("endo_percussion","Tenderness on percussion", "checkbox"),
        ExamField("endo_swelling",  "Swelling/sinus tract",     "checkbox"),
    ],
    "Oral Surgery Examination": [
        ExamField("surg_impacted",   "Impacted tooth position",       "text"),
        ExamField("surg_trismus",    "Trismus",                       "text"),
        ExamField("surg_cellulitis", "Facial cellulitis",             "checkbox"),
        ExamField("surg_fracture",   "Fracture signs",                "checkbox"),
        ExamField("surg_socket",     "Post-extraction socket status", "text"),
    ],
}

EXAM_GROUPS: list[dict] = [
    {
        "title": "General & Extraoral",
        "categories": ["General Examination", "Extraoral Examination"],
    },
    {
        "title": "Intraoral Examination",
        "categories": ["Intraoral Soft Tissue Examination", "Hard Tissue Examination"],
    },
    {
        "title": "Specialty Evaluations",
        "categories": [
            "Periodontal Examination",
            "Orthodontic Examination",
            "Prosthodontic Examination",
            "Endodontic Examination",
            "Oral Surgery Examination",
        ],
    },
]