from app.taxonomy.types import MedicalHistoryItem

MEDICAL_HISTORY_TAXONOMY: dict[str, list[MedicalHistoryItem]] = {
    "Systemic Diseases": [
        MedicalHistoryItem("DiabetesMellitus",   "Diabetes mellitus",         "warning"),
        MedicalHistoryItem("Hypertension",       "Hypertension",              "warning"),
        MedicalHistoryItem("Asthma",             "Asthma",                    "warning"),
        MedicalHistoryItem("Tuberculosis",       "Tuberculosis",              "critical"),
        MedicalHistoryItem("ThyroidDisorder",    "Thyroid disorder",          "info"),
        MedicalHistoryItem("HeartDisease",       "Heart disease",             "critical"),
        MedicalHistoryItem("KidneyDisease",      "Kidney disease",            "critical"),
        MedicalHistoryItem("LiverDisease",       "Liver disease",             "warning"),
        MedicalHistoryItem("EpilepsySeizure",    "Epilepsy/seizure disorder", "critical"),
        MedicalHistoryItem("StrokeParalysis",    "Stroke/paralysis",          "critical"),
        MedicalHistoryItem("Arthritis",          "Arthritis",                 "info"),
        MedicalHistoryItem("Cancer",             "Cancer",                    "critical"),
        MedicalHistoryItem("HivAids",            "HIV/AIDS",                  "critical"),
        MedicalHistoryItem("Hepatitis",          "Hepatitis",                 "critical"),
        MedicalHistoryItem("BleedingDisorders",  "Bleeding disorders",        "critical"),
        MedicalHistoryItem("Anemia",             "Anemia",                    "warning"),
        MedicalHistoryItem("GastricUlcerGerd",   "Gastric ulcer/GERD",        "info"),
        MedicalHistoryItem("CopdLungDisease",    "COPD/chronic lung disease", "warning"),
        MedicalHistoryItem("Osteoporosis",       "Osteoporosis",              "info"),
        MedicalHistoryItem("PsychiatricIllness", "Psychiatric illness",       "info"),
    ],
    "Past Medical History": [
        MedicalHistoryItem("PrevHospitalization", "Previous hospitalization",   "info"),
        MedicalHistoryItem("PrevSurgery",         "Previous surgery",           "warning"),
        MedicalHistoryItem("BloodTransfusion",    "Blood transfusion history",  "warning"),
        MedicalHistoryItem("MajorIllnessPast",    "Major illness in past",      "info"),
        MedicalHistoryItem("PrevTraumaInjury",    "Previous trauma/injury",     "info"),
        MedicalHistoryItem("IcuAdmission",        "History of ICU admission",   "critical"),
    ],
    "Drug History": [
        MedicalHistoryItem("CurrentMeds",           "Current medications",        "warning"),
        MedicalHistoryItem("LongTermSteroid",       "Long-term steroid use",      "critical"),
        MedicalHistoryItem("AnticoagulantTherapy",  "Anticoagulant therapy",      "critical"),
        MedicalHistoryItem("InsulinHypoglycemics",  "Insulin/oral hypoglycemics", "warning"),
        MedicalHistoryItem("AntihypertensiveDrugs", "Antihypertensive drugs",     "warning"),
        MedicalHistoryItem("AllergyMedications",    "Allergy to medications",     "critical"),
    ],
    "Allergy History": [
        MedicalHistoryItem("PenicillinAllergy",      "Penicillin allergy",       "critical"),
        MedicalHistoryItem("LocalAnestheticAllergy", "Local anesthetic allergy", "critical"),
        MedicalHistoryItem("FoodAllergy",            "Food allergy",             "warning"),
        MedicalHistoryItem("LatexAllergy",           "Latex allergy",            "critical"),
        MedicalHistoryItem("DustPollenAllergy",      "Dust/pollen allergy",      "info"),
    ],
    "Personal History": [
        MedicalHistoryItem("Smoking",           "Smoking",               "warning"),
        MedicalHistoryItem("TobaccoChewing",    "Tobacco chewing",       "warning"),
        MedicalHistoryItem("AlcoholConsumption","Alcohol consumption",   "info"),
        MedicalHistoryItem("BetelNutHabit",     "Betel nut/gutkha habit","warning"),
        MedicalHistoryItem("DietHistory",       "Diet history",          "info"),
        MedicalHistoryItem("SleepPattern",      "Sleep pattern",         "info"),
    ],
    "Family History": [
        MedicalHistoryItem("FamilyDiabetes",     "Diabetes in family",       "info"),
        MedicalHistoryItem("FamilyHypertension", "Hypertension in family",   "info"),
        MedicalHistoryItem("FamilyCancer",       "Cancer history in family", "info"),
        MedicalHistoryItem("GeneticDisorders",   "Genetic disorders",        "warning"),
        MedicalHistoryItem("FamilyHeartDisease", "Heart disease in family",  "info"),
    ],
}

DENTAL_RELEVANT_QUESTIONS: list[MedicalHistoryItem] = [
    MedicalHistoryItem("Q_Diabetic",          "Are you diabetic?",                         "warning"),
    MedicalHistoryItem("Q_Hypertension",      "Do you have high blood pressure?",          "warning"),
    MedicalHistoryItem("Q_HeartProblem",      "Any heart problem or surgery?",             "critical"),
    MedicalHistoryItem("Q_MedicineAllergies", "Any allergies to medicines?",               "critical"),
    MedicalHistoryItem("Q_BloodThinners",     "Are you taking blood thinners?",            "critical"),
    MedicalHistoryItem("Q_HepatitisTB",       "Any history of hepatitis or tuberculosis?", "critical"),
    MedicalHistoryItem("Q_Pregnant",          "Are you pregnant?",                         "info"),
    MedicalHistoryItem("Q_SmokeAlcohol",      "Do you smoke or consume alcohol?",          "info"),
]